### PR TITLE
Added missing files and improved README

### PR DESCRIPTION
**Pull request by riverma**
## Purpose
- Ensuring compliance with leaderboard best practices. See: https://github.com/unity-sds/unity-project-management/blob/main/standards-compliance/leaderboard.md
## Proposed Changes
- [CHANGE] README contents
- [ADD] Issue templates and pull request templates
## Issues
- N/A
## Testing
- GitHub markdown preview: https://github.com/riverma/unity-py/blob/rverma-patch-1/README.md

### CODE REVIEW

**Comment by riverma** [comment]
Note @anilnatha: please add a screenshot of the unity.py tool to the README in the top `[INSERT SCREENSHOT...` line mentioned here: https://github.com/riverma/unity-py/blame/rverma-patch-1/README.md#L16

**Comment by rtapella** [comment]
@riverma for libraries like this… what do you suggest for a screenshot? The pypi web page for unity-sds-client? A screenshot of python code that uses the library? A screenshot of the library code itself? Something else?

**Comment by riverma** [comment]
> @riverma for libraries like this… what do you suggest for a screenshot? The pypi web page for unity-sds-client? A screenshot of python code that uses the library? A screenshot of the library code itself? Something else?

Hi @rtapella - thanks for that. Since this is a user-interface of sorts, I was thinking it would be useful to have a screenshot (or GIF!) of say a terminal window and some sample commands in action. Doing so would quickly communicate the utility of using `unity-py`. What do you think?

**Comment by anilnatha** [comment]
@rtapella we spoke of adding code samples in lieu of screenshots, if you're still good with that let me know so that I can remove the placeholder screenshot callout, before approving and merging this PR.

**Comment by riverma** [comment]
> @rtapella we spoke of adding code samples in lieu of screenshots, if you're still good with that let me know so that I can remove the placeholder screenshot callout, before approving and merging this PR.

@anilnatha @rtapella - code samples in place of screens is great, probably more useful given the nature of the `unity-py` tool. LGTM!

**Review by rtapella — APPROVED** [review]
yeah I am good with code samples.

**Review by mike-gangl — APPROVED** [review]

**Pull request merged**
