### PR TITLE
Merge `develop` to `main` to address package naming.

### PR DESCRIPTION
**Pull request by anilnatha**
This PR addresses the need to update the package name so users can reference the name unity_sds_client when importing the package and not unity_py. This way the imports match the name used when installing from PyPi and to get this change into the `main` branch so that we may publish it to PyPi.

### CODE REVIEW

**Comment by rtapella** [comment]
Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?

Also how do we document this? Can we just run some auto-doc thing?

**Comment by mike-gangl** [comment]
@rtapella publishing to pypi is done when a "release" is created from the main branch. we should document that process.

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Comment by anilnatha** [comment]
> Once we finish these updates... how does it get pushed into Pypi? Manually? Is the process linked/documented here?
> 
> Also how do we document this? Can we just run some auto-doc thing?

Early on I tinkered with `pdoc`, wonder if we can use a github action to generate the docs and publish them to Github pages

**Pull request merged**
