### PR TITLE
Add health service

### PR DESCRIPTION
**Pull request by anilnatha**
## Purpose

Initial implementation of a health service to convey the health state of the system. This implementation is using a stubbed in set of data until we can integrate an API call to fetch the health data for a given project/venue when the API endpoint is implemented.

## Proposed Changes
- Added Health Service that provides features to fetch and print the health state of the system.
- Changed printing of unity objects so that they include the health status report.
- Updated changelog and version number of unity-py, currently marked as 'unreleased' in CHANGELOG.
## Issues
- #86
## Testing
- Created initial unit tests to ensure fetching, report generation, and printing of health report are functional

### CODE REVIEW

**Review by rtapella — APPROVED** [review]
fix linting. other than that, ok

**Comment by anilnatha** [comment]
Thanks @rtapella, yup, I'm working on the linting right now.

**Comment by anilnatha** [comment]
@mike-gangl I fixed the linting errors that were being reported in the checks; however, now we're having an issue with coveralls and all it reports is:

```
🔍 Detected coverage file: .coverage
🚨 Nothing to report
Error: Process completed with exit code 1.
```

Have you come across this issue in the past?

**Comment by mike-gangl** [comment]
not sure why the coverage dropped to 50%, but that's something we'll want to increase coverage on in the future.

**Comment by mike-gangl** [comment]
You're free to merge this check in now. i had to update the version of the coverage, but also change the coverage report being generated by pytest. ther was something "under the good" that was causing the coverage formatting to be invalid.

**Pull request merged**
